Support cgroup v2
groove-x/cgroup-exporter pull request #5
Opened 2021-02-27 12:06 UTC by MatMaul

For now RSS, open FDs and sockets are not supported.

2021-02-27 23:22 UTC, MatMaul commented
There is also a second commit adding total cpu usage (vs only user).
I didn't push an independent PR because it would conflict, but I can remove it and send it later (after the first is merged) if you want.
Since it is pretty small, simple and in an independent commit I thought it was ok to bundle it.

2021-02-27 23:24 UTC, MatMaul commented
Oh I forgot it also add mem+swap metric hum. let me know if you want to break it further completely or if this is fine for review.

2021-04-30 07:31 UTC, atotto commented
Thank you for your PR! I will review this commit.

2021-04-30 08:50 UTC, atotto requested changes

2021-04-30 08:50 UTC, atotto commented on main.go
> +		# TYPE container_cpu_seconds_total counter`)
trim space
```suggestion
# TYPE container_cpu_seconds_total counter`)
```

2021-04-30 08:50 UTC, atotto commented on main.go
> +	}
yes, shoud we support hybrid version here.
```suggestion
	if cgroups.Mode() == cgroups.Unified {
		return map[string]*cgroupV1Metrics{}, nil
	}
```

2021-04-30 15:43 UTC, MatMaul commented
Thanks for the review ! I merged your suggestions.

2021-05-05 23:29 UTC, atotto approved these changes

2021-05-06 00:48 UTC, atotto commented
Did you get the container_memsw_usage_bytes metrics in cgroup-v1 (Legacy and Hybrid) system?

I cannot read it (all container_memsw_usage_bytes are zero)
```
container_memsw_usage_bytes{id="/system.slice/ssh.service"} 0
container_memsw_usage_bytes{id="/system.slice/avahi-daemon.service"} 0
container_memsw_usage_bytes{id="/system.slice/NetworkManager.service"} 0
```

We need test environment..

2025-08-06 02:17 UTC, merged